# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: JekyllOrg
description: > # this means to ignore newlines until "baseurl:"
  a free Jekyll theme for organizations and non-profits
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost:4000" # the base hostname & protocol for your site

# Profiles
facebook_username: damianeoloan
github_username: damianeoloan
googleplus_username: damianeoloan
instagram_username: damianeoloan
linkedin_username: damianeoloan
periscope_username: damianeoloan
reddit_username: damianeoloan
twitter_username: damianeoloan
youtube_username: damianeoloan
email: damianoloan0@gmail.com

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

# Blog / news url
permalink: /news/:title/

# Mentions
jekyll-mentions: https://twitter.com

# Collections
collections:
  services:
    title: Services
    featured-image:
    permalink: /services/:path
    output: true
  issues:
    title: Issues
    featured-image:
    permalink: /issues/:path
    output: true
  events:
    title: Events
    featured-image:
    permalink: /events/:path
    output: true

# Prose
prose:
  rooturl: '/'
  siteurl: 'https://127.0.0.1:4000'
  media: 'media'
  ignore:
    - /_layouts
    - /_includes
    - /_sass
  metadata:
